name: duck_router

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - "duck_router/**"
      - ".github/workflows/duck_router.yaml"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: duck_router

    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v4

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ vars.FLUTTER_VERSION }}
          channel: "stable"

      - name: Install Dependencies
        run: |
          flutter pub global activate very_good_cli
          very_good packages get

      - name: ✨ Check Formatting
        run: dart format --set-exit-if-changed lib test

      - name: 🕵️ Analyze
        run: flutter analyze lib test

      - name: 🧪 Run Tests
        run: very_good test -j 4 --optimization --test-randomize-ordering-seed random
